FROM python:3.12-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the run.py file
COPY ./python/run.py .

# Set an environment variable to name the experiment
ENV EXPERIMENT_NAME="Python3_12"

# Set an environment variable to store dataset file name
ENV DATASET_FILE="sampled-exponential-and-polynomial-regexes.json"

CMD ["python", "run.py"]
