FROM node:22.2.0

# Set the working directory
WORKDIR /usr/src/app

# Copy the regexWorker.js file
COPY ./javascript/regexWorker.js .

# Copy the run.js file
COPY ./javascript/run.js .

# Set an environment variable to name the experiment
ENV EXPERIMENT_NAME="NodeV22_2_0"

# Set an environment variable to store dataset file name
ENV DATASET_FILE="sampled-exponential-and-polynomial-regexes.json"

CMD ["node", "--enable-experimental-regexp-engine", "run.js"]
